config/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("core.urls", namespace="core")),
    path("users/", include("users.urls", namespace="users")),
    path("books/", include("books.urls")),
    path("lists/", include("lists.urls", namespace="lists")),
    path("accounts/", include("allauth.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
# urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
# urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from books import views as book_views


app_name = "core"


urlpatterns = [
    path("", book_views.BookList.as_view(), name="home"),
]

lists/urls.py
from django.urls import path

from .views import list_home, add_list, remove_list

from . import views

app_name = "lists"

urlpatterns = [
    path("", views.list_home, name="list-home"),
    path("add/<int:book_id>", views.add_list, name="add-list"),
    path("remove/<int:book_id>", views.remove_list, name="remove-list"),
]

lists/models.py
from django.conf import settings
from django.db import models

# Create your models here.

User = settings.AUTH_USER_MODEL


class ListManager(models.Manager):
    def new_or_get(self, request):
        list_id = request.session.get("list_id", None)
        qs = self.get_queryset().filter(id=list_id)
        if qs.count() == 1:
            new_obj = False
            list_obj = qs.first()
            if request.user.is_authenticated and list_obj.user is None:
                list_obj.user = request.user
                list_obj.save()
        else:
            list_obj = List.objects.new(user=request.user)
            new_obj = True
            request.session["list_id"] = list_obj.id
        return list_obj, new_obj

    def new(self, user=None):
        # print(user)
        if user is not None:
            if user.is_authenticated:
                user_obj = user
        return self.model.objects.create(user=user_obj)


class List(models.Model):

    """ List Model Definition """

    user = models.ForeignKey(User, related_name="lists", on_delete=models.CASCADE)
    books = models.ManyToManyField("books.Book", related_name="lists", blank=True)

    objects = ListManager()

    def __str__(self):
        return str(self.id)

lists/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required

from django.contrib import messages

from books.models import Book
from .models import List

# Create your views here.


def list_home(request):
    list_obj, new_obj = List.objects.new_or_get(request)
    return render(request, "lists/list_home.html", {"list": list_obj})


@login_required
def add_list(request, book_id):

    if book_id is not None:
        try:
            book_obj = Book.objects.get(id=book_id)
        except Book.DoesNotExist:
            # print("Show message to user, book is gone?")
            return redirect("lists:list-home")
        list_obj, new_obj = List.objects.new_or_get(request)
        if book_obj in list_obj.books.all():
            messages.success(request, f"이미 목록에 있습니다.")
            return redirect(book_obj.get_absolute_url())
            # list_obj.books.remove(book_obj)
        else:
            list_obj.books.add(book_obj)

    return redirect("lists:list-home")


@login_required
def remove_list(request, book_id):
    book_obj = get_object_or_404(Book, id=book_id)
    list_obj, new_obj = List.objects.new_or_get(request)
    if book_obj in list_obj.books.all():

        if list_obj.books.count() > 1:
            list_obj.books.remove(book_obj)
            list_obj.save()
        else:
            list_obj.delete()
    return redirect("lists:list-home")

templates/lists/add_list.html
{% load static %}

<!doctype html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
        integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous"> -->
    <link rel="stylesheet" href="/static/bootstrap.min (7).css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/css/all.min.css">
    <!--<link rel="stylesheet" href="{% static 'widgets/rateit.js/rateit.css' %}">
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"
        integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>
    <script src="{% static 'widgets/rateit.js/jquery.rateit.min.js' %}"></script>-->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
        integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
        integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
        crossorigin="anonymous"></script>
    <title></title>
</head>

<body>



    <div>
        <div class="text-center">
            <br>
            <h1 class="class">Your Book List</h1>
            <br>
        </div>
    </div>

    <div class="container">
        <div class="row">
            {% if list.books.exists %}
            {% for book in list.books.all %}

            <div class="col-sm">
                <div class="card" style="width: 13rem; ">
                    <img src="{{book.image.url}}" style="border-radius: 6px; height:18rem;" alt="" class="">
                    <a class="btn btn-info" href="{% url 'lists:remove-list' book.id %}">Delete</a>
                </div>
                <br />
            </div>
            {% endfor %}
            {% else %}
            <h3 style="margin: auto;">" Your Book List is empty. "</h3>
            {% endif %}
        </div>
    </div>


</body>

</html>

templates/lists/list_home.html
{% extends '_base.html' %}

{% load static %}
{% load crispy_forms_tags %}
{% block content %}



<h1 class="col-5 mt-1">Favorite Book Page</h1>






{% include 'lists/add_list.html' with book=object list=list %}

{% endblock %}