books/urls.py
from django.urls import path

from .views import BookList, BookDetail, search

from . import views

app_name = "books"

urlpatterns = [
    path("", BookList.as_view(), name="list"),
    path("search/", views.search, name="search"),
    path("<int:pk>/", BookDetail.as_view(), name="detail"),
    path("<int:pk>/new_review/", views.review_create, name="review-create"),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("core.urls", namespace="core")),
    path("users/", include("users.urls", namespace="users")),
    path("books/", include("books.urls")),
    path("lists/", include("lists.urls", namespace="lists")),
    path("accounts/", include("allauth.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
# urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
# urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from books import views as book_views


app_name = "core"


urlpatterns = [
    path("", book_views.BookList.as_view(), name="home"),
]

lists/urls.py
from django.urls import path

from .views import list_home, add_list, remove_list

from . import views

app_name = "lists"

urlpatterns = [
    path("", views.list_home, name="list-home"),
    path("add/<int:book_id>", views.add_list, name="add-list"),
    path("remove/<int:book_id>", views.remove_list, name="remove-list"),
]

books/models.py
from django.urls import reverse

from django.db import models

from django.core.validators import MinValueValidator, MaxValueValidator

# Create your models here.


STATUS_CHOICES = (
    ("RA", "RECENTLY ADDED"),
    ("MR", "MOST READ"),
    ("TR", "TOP RATED"),
)

# REVIEW_POINT_CHOICES = (("1", 1), ("2", 2), ("3", 3), ("4", 4), ("5", 5))


class Book(models.Model):
    
    title = models.CharField(max_length=100, unique=True)
    author = models.CharField(max_length=70)
    description = models.TextField(blank=True, null=True)
    image = models.ImageField(upload_to="book")
    publish_data = models.DateField()
    purchase_site = models.URLField(max_length=1000, default=False)
    status = models.CharField(choices=STATUS_CHOICES, max_length=2)

    # 조회수
    views_count = models.IntegerField(default=0)

    class Meta:
        ordering = [
            "title",
        ]

    def __str__(self):
        return self.title

    def total_rating(self):
        all_reviews = self.reviews.all()
        all_ratings = 0
        if len(all_reviews) > 0:
            for review in all_reviews:
                all_ratings += review.point_average()
            # print(review.rating_average())
            return all_ratings / len(all_reviews)
        return 0

    def get_absolute_url(self):
        return reverse("books:detail", kwargs={"pk": self.pk})
        # return "/books/{}/".format(self.pk)

    @property
    def update_counter(self):
        self.views_count = self.views_count + 1
        self.save()


class Review(models.Model):
    point = models.IntegerField(validators=[MinValueValidator(1), MaxValueValidator(5)])
    content = models.TextField()
    user = models.ForeignKey(
        "users.User", related_name="reviews", on_delete=models.CASCADE
    )
    book = models.ForeignKey(
        "books.Book", related_name="reviews", on_delete=models.CASCADE
    )

    def __str__(self):
        return (
            f"{self.content} - {self.book}"  #  return self.review, return self.room 등등
        )

    def point_average(self):
        point_count = (
            Review.objects.filter().count()
        )  # book, book_id, content, id, point, user, user_id
        avg = self.point / point_count
        return round(avg, 2)

    def get_absolute_url(self):
        return self.book.get_absolute_url() + "#review-id-{}".format(self.pk)

books/forms.py
from django import forms

from .models import Review


REVIEW_POINT_CHOICES = (("1", 1), ("2", 2), ("3", 3), ("4", 4), ("5", 5))


class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = [
            "point",
            "content",
        ]
        labels = {"point": ("평점"), "content": ("리뷰를 남겨주세요.")}

        widgets = {
            "content": forms.TextInput(),
            "point": forms.Select(choices=REVIEW_POINT_CHOICES),
        }

books/views.py
from django.shortcuts import render, redirect, reverse, get_object_or_404
from django.http import Http404
from django.contrib.auth.decorators import login_required
from django.views.generic import ListView, DetailView

from users.models import User
from .models import Book, Review
from .forms import ReviewForm
from . import forms

# Create your views here.


class BookList(ListView):
    model = Book
    template_name = "books/book_list.html"


class BookDetail(DetailView):
    model = Book
    queryset = Book.objects.all()

    # context_object_name = "book"
    template_name = "books/book_detail.html"

    def get_object(self, *args, **kwargs):
        object = super().get_object()
        object.views_count += 1
        object.save()
        return object

    def get_context_data(self, **kwargs):
        context = super(BookDetail, self).get_context_data(**kwargs)
        context["form"] = ReviewForm()
        return context


def review_create(request, pk):
    book = get_object_or_404(Book, pk=pk)

    errors = []
    if request.method == "POST":
        form = ReviewForm(request.POST)
        if form.is_valid():
            review = form.save(commit=False)
            review.book = book
            review.user = request.user
            review.save()

            if not review.content:
                errors.append("댓글을 입력해주세요.")

            return redirect(book.get_absolute_url())
    else:
        form = ReviewForm()
    return render(request, "books/book_detail.html", {"form": form})


def search(request):

    books = Book.objects.all().order_by("-id")
    # qs = Board.objects.all()
    search = request.GET.get("search")

    if not search == "" and search is not None:
        books = books.filter(title__icontains=search)

    return render(request, "books/search.html", {"books": books, "search": search})

templates/books/book_detail.html
{% extends '_base.html' %}

{% load static %}
{% load crispy_forms_tags %}
{% block content %}
{% load i18n %}

<body>


    <div class="container">
        <div class="row mt-5">
            <div class="col-md-3 mt-4">
                <div class="card mb-4 shadow-0" style="border-color: transparent;border-style: hidden;">
                    <img src="{{ book.image.url }}" style="height:300px;">
                    <div class="card-body" style="margin: auto;">
                        <div class="d-flex justify-content-between align-items-center">
                            <small class="text-muted">리뷰 수 : {{ book.views_count }}</small>
                            <br>
                        </div>

                        <div class="d-flex justify-content-between align-items-center">
                            <small class="text-muted">
                                <tr>
                                    <th>
                                        <div style="font-size:13px; ">Rating</div>
                                    </th>
                                </tr>
                                <tr>
                                    <td>
                                        <div style=" background-color: #7B68EE;top:0; left:0; height:19px;width:30pxz-index:100; width:
                                        calc(20% * {{ book.total_rating }})">
                                            <img style="display: inline-block; height:23px;"
                                                src="{% static 'image/stars.png' %}" alt="{{ book.total_rating }}"
                                                title="{{ book.total_rating }}">
                                        </div>
                                    </td>
                                </tr>
                            </small>
                            <br>
                        </div>

                        <div class="d-flex justify-content-between align-items-center" style="margin-top: 7px;">
                            <a href="{% url 'lists:add-list' book.id %}"
                                class="btn btn-primary my-2">{% trans "Save to My Lists" %}</a>
                            <br>
                        </div>
                    </div>
                </div>
            </div>
            <div class=" col-md-9 ">
                <div class="card mb-6 shadow-0" style="border-color: transparent;border-style: hidden;">
                    <div class="card-body">
                        <h2 style="color:#708090">{{ book.title }}</h6>
                            <br>
                            <p>{{ book.author }}</p>

                            <small class="text-muted">{{ book.publish_data }}</small>
                            <hr>
                            <p class="card-text">{{ book.description }}</p>
                            <div class="d-flex justify-content-between align-items-center">
                                <div class="btn-group">
                                    <a href="{{ book.purchase_site }}" class="btn btn-primary my-2">
                                        구매하러 가기</a>
                                </div>
                                <small class="text-muted"></small>
                            </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    {% if messages %}
    {% for message in messages %}
    <div class="alert alert-{{ message.tags }}">{{ message }}</div>

    {% endfor %}
    {% endif %}

    <!-- 댓글 리스트 -->
    <div class="container" style="margin-top: 30px;">
        <div class="row mt-10">
            <div class="col-md-12 comment-bg">
                <div class="page-header">
                    <h1>Reviews</h1>
                </div>
                <div class="col-lg-8 col-md-10 mx-auto" style="margin: 60px;">
                    {% for review in book.reviews.all %}
                    <div class="media" id="review-id-{{ review.pk }}">
                        <div class="media-body">
                            <div class="avatar" style="display: flex;">
                                {% if review.user.socialaccount_set.all.0.get_avatar_url %}
                                <img width="50px" class="d-flex mr-3 rounded-circle"
                                    src="{{ review.user.socialaccount_set.all.0.get_avatar_url }}" alt="">
                                {% else %}
                                <img width="50px" class="d-flex mr-3 rounded-circle"
                                    src="https://api.adorable.io/avatars/285/{{ review.user }}.png" alt="">
                                {% endif %}

                                <h5 class="media-heading user_name mt-3" style="margin: 0;">
                                    {{ review.user.username }}
                                </h5>

                                <small class="text-muted" style="margin: auto;">
                                    <div style="width:100px; position:relative; height:10px;">
                                        <tr>
                                            <td>
                                                <div style=" background-color: #7B68EE;top:0; left:0; height:auto;width:30pxz-index:100; width:
            calc(20% * {{ review.point }})">
                                                    <img style="display: inline-block; height:22.5px; width:100px;"
                                                        src="{% static 'image/stars.png' %}" alt="{{ review.point }}"
                                                        title="{{ review.point }}">
                                                </div>
                                            </td>
                                    </div>
                                </small>
                            </div>
                            <br>
                            {{ review.content }}
                            <hr>
                        </div>
                    </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>

    <!-- 댓글 등록하기 -->
    <div class="card" style="width: 50rem; margin: auto;">
        <h5 class="card-header">Leave a Comment:</h5>
        <div class="card-body">
            {% if user.is_authenticated or request.session.users %}
            <form method="post" action="{{ object.get_absolute_url }}new_review/">
                {% csrf_token %}
                <div class="form-group">
                    {{ form|crispy }}
                </div>
                <button type="submit" class="btn btn-primary">Submit</button>
            </form>
            {% else %}
            <a class="btn btn-outline-dark btn-block" href="{% url 'account_login' %}" role="button">로그인</a>
            {% endif %}
        </div>
    </div>
    <br>
    <br>

    {% endblock %}

templates/books/book_list.html
{% extends 'base.html' %}

{% block content %}

<div class="container">
    <h2 style="color:#383838; text-align: center; margin-bottom: 30px; margin-top: 150px;">새로나온 책
    </h2>
    <div class="row">
        {% for book in object_list %}
        {% if book.status == 'RA' %}

        <div class="col-sm">
            <div class="card" style="width: 12rem; ">
                <a href="{% url 'books:detail' pk=book.id %}" class="btn btn-transparent"><img class="card-img-top"
                        src="{{ book.image.url }}" style="height:15rem;"></a>
            </div>
            <br />
        </div>
        {% endif %}
        {% endfor %}
    </div>
</div>




{% endblock %}

templates/books/search.html
{% extends '_base.html' %}

{% load static %}

{% block content %}


<br>

<br>
<div class="jumbotron jumbotron-fluid">
    <div class="container">
        <h1 class="display-4">Search Results </h1>
        <p class="lead">{{ search }} 의 검색 결과입니다.</p>
    </div>
</div>

<div class="container">
    <div class="row">
        {% for book in books %}

        <div class="card" style="width: 18rem; margin:auto; margin-top: 30px;">
            <a href="{{ book.get_absolute_url }}"><img src="{{book.image.url}}" class="card-img-top"></a>
            <div class="card-body">
                <h5 class="card-title">{{ book.title }}</h5>
            </div>
            {% empty %}
            <h5 style="margin: auto;">" No results found. "</h5>
            {% endfor %}
        </div>
    </div>
</div>


{% endblock %}