books/urls.py
from django.urls import path

from .views import BookList, BookDetail, search

from . import views

app_name = "books"

urlpatterns = [
    path("", BookList.as_view(), name="list"),
    path("search/", views.search, name="search"),
    path("<int:pk>/", BookDetail.as_view(), name="detail"),
    path("<int:pk>/new_review/", views.review_create, name="review-create"),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("core.urls", namespace="core")),
    path("users/", include("users.urls", namespace="users")),
    path("books/", include("books.urls")),
    path("lists/", include("lists.urls", namespace="lists")),
    path("accounts/", include("allauth.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
# urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
# urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from books import views as book_views


app_name = "core"


urlpatterns = [
    path("", book_views.BookList.as_view(), name="home"),
]

lists/urls.py
from django.urls import path

from .views import list_home, add_list, remove_list

from . import views

app_name = "lists"

urlpatterns = [
    path("", views.list_home, name="list-home"),
    path("add/<int:book_id>", views.add_list, name="add-list"),
    path("remove/<int:book_id>", views.remove_list, name="remove-list"),
]

templates/_base.html
{% load static %}
{% load crispy_forms_tags %}
<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Jekyll v3.8.6">
    <title>Good Readers</title>

    <script src="https://code.jquery.com/jquery-3.4.1.min.js"
        integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>

    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
        integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
        integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
        crossorigin="anonymous"></script>
    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min (7).css' %}" />
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />
    <!--<link rel="stylesheet" href="/static/bootstrap.min (7).css" /> -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/css/all.min.css">

</head>

<!-- Custom styles for this template -->

</head>

<body>
    <nav class="site-header sticky-top py-1">
        <div class="container d-flex flex-column flex-md-row justify-content-between">

            <a class="py-2 d-none d-md-inline-block" href="{% url 'core:home' %}">Home</a>
            {% if user.is_authenticated %}
            <a class="py-2 d-none d-md-inline-block">{{ user.username }}님, 반갑습니다.</a>
            <a class="py-2 d-none d-md-inline-block" href="{% url 'lists:list-home' %}">My Lists</a>
            <a class="py-2 d-none d-md-inline-block" href="/users/profile/">Profile</a>
            <a class="py-2 d-none d-md-inline-block" href="{% url 'account_logout' %}">Logout</a>
            {% else %}
            <a class="py-2 d-none d-md-inline-block" href="{% url 'account_login' %}">Login</a>
            <a class="py-2 d-none d-md-inline-block" href="{% url 'account_signup' %}">Register</a>
            {% endif %}
        </div>
    </nav>

    <nav class="navbar navbar-dark bg-dark" style="display: flex;">
        <a href="{% url 'core:home' %}" class="navbar-brand">GoodReads</a>
        </div>
    </nav>

    {% block content %}
    {% endblock %}
    <hr>
    <footer class="container py-5">
        <div class="row" style="text-align: center; padding-top: 30px;">
            <div class="col-6 col-md">
                <a class="py-2">
                    <i class="fas fa-book fa-2x" style="width:26px; height:26px;"></i>
                </a>
                <small class="d-block mb-3 text-muted" style="margin-top: 6px;">&copy; 2020, made by Yubin Cho.
                </small>
            </div>


            <div class="col-6 col-md" style="margin-bottom: 30px; ">
                <h5>Contact</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="mailto:yubincho9@gmail.com">yubincho9@gmail.com</a></li>
                </ul>
            </div>
        </div>
    </footer>
</body>

</html>

templates/base.html
{% load static %}
{% load crispy_forms_tags %}
<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Jekyll v3.8.6">
    <title>Good Readers</title>

    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min (7).css' %}" />
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />
    <script src="{% static 'js/script.js' %}"></script>
    <!--<link rel="stylesheet" href="/static/bootstrap.min (7).css" /> -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/css/all.min.css">

    <script src="https://code.jquery.com/jquery-3.4.1.min.js"
        integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>

    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
        integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
        integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
        crossorigin="anonymous"></script>

    <!-- Custom styles for this template -->

</head>

<body>

    <nav class="site-header sticky-top py-1">
        <div class="container d-flex flex-column flex-md-row justify-content-between">
            <a class="py-2" aria-label="Product">
                <i class="fas fa-book fa-2x" style="width:26px; height:26px;"></i>
            </a>
            {% if user.is_authenticated %}
            <a class="py-2 d-none d-md-inline-block">{{ user.username }}님, 반갑습니다.</a>
            <a class="py-2 d-none d-md-inline-block" href="{% url 'lists:list-home' %}">My Lists</a>
            <a class="py-2 d-none d-md-inline-block" href="/users/profile/">Profile</a>
            <a class="py-2 d-none d-md-inline-block" href="{% url 'account_logout' %}">Logout</a>
            {% else %}
            <a class="py-2 d-none d-md-inline-block" href="{% url 'account_login' %}">Login</a>
            <a class="py-2 d-none d-md-inline-block" href="{% url 'account_signup' %}">Register</a>
            {% endif %}
        </div>
    </nav>

    <nav class="navbar navbar-dark bg-dark" style="display: flex;">
        <a href="{% url 'core:home' %}" class="navbar-brand">GoodReads</a>
        <div class="col-8">
            <form class="form-inline " method=" GET" action="{% url 'books:search' %}">
                {% csrf_token %}
                <div class="col-5">
                    <input class="form-control " style="width:300px;" name="search" type="text" placeholder="&#xf002 ">
                </div>
                <div class="col-2">
                    <button class="btn btn-secondary" type="submit">Search</button>
                </div>

            </form>
        </div>
    </nav>


    <main role="main">
        <div style="margin-top: 100px;">
            <h2 style=" text-align: center;">베스트 & 스테디 셀러</h2>
            <div class="slide_wrapper">
                <ul class="slides">
                    {% for book in object_list %}
                    {% if book.status == 'TR' or book.status == 'MR' %}
                    <li><a href="{% url 'books:detail' pk=book.id %}"><img src="{{ book.image.url }}"
                                style="width: 12rem; height:17rem;" alt=""></a></li>
                    {% endif %}
                    {% endfor %}
                </ul>

            </div>
            <p class="controls">
                <span class="prev"><i class="fas fa-chevron-left"></i></span>
                <span class="next"><i class="fas fa-chevron-right"></i></span>
            </p>
        </div>
        </div>


        {% block content %}
        {% endblock %}
    </main>
    <hr>
    <footer class="container py-5">
        <div class="row" style="text-align: center; padding-top: 30px;">
            <div class="col-6 col-md">
                <a class="py-2">
                    <i class="fas fa-book fa-2x" style="width:26px; height:26px;"></i>
                </a>
                <small class="d-block mb-3 text-muted" style="margin-top: 6px;">&copy; 2020, made by Yubin Cho.
                </small>
            </div>


            <div class="col-6 col-md" style="margin-bottom: 30px; ">
                <h5>Contact</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="mailto:yubincho9@gmail.com">yubincho9@gmail.com</a></li>
                </ul>
            </div>
        </div>
    </footer>
    <script>
        var slides = document.querySelector('.slides'),
            slide = document.querySelectorAll('.slides li'),
            currentIdx = 0,
            slideCount = slide.length,
            prevBtn = document.querySelector('.prev'),
            slideWidth = 300,
            slideMargin = 30,
            nextBtn = document.querySelector('.next');

        slides.style.width = (slideWidth + slideMargin) * slideCount - slideMargin + 'px';

        function moveSlide(num) {
            slides.style.left = -num * 330 + 'px';
            currentIdx = num;
        }
        nextBtn.addEventListener('click', function () {
            if (currentIdx < slideCount - 3) {
                moveSlide(currentIdx + 1);
                console.log(currentIdx);
            } else {
                moveSlide(0);
            }

        });
        prevBtn.addEventListener('click', function () {
            if (currentIdx > 0) {
                moveSlide(currentIdx - 1);

            } else {
                moveSlide(slideCount - 3);
            }

        });
    </script>

</body>

</html>