config/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("core.urls", namespace="core")),
    path("users/", include("users.urls", namespace="users")),
    path("books/", include("books.urls")),
    path("lists/", include("lists.urls", namespace="lists")),
    path("accounts/", include("allauth.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
# urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
# urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from books import views as book_views


app_name = "core"


urlpatterns = [
    path("", book_views.BookList.as_view(), name="home"),
]

users/urls.py
from django.urls import path
from . import views

# from .views import RegisterView, LoginView

app_name = "users"

urlpatterns = [
    path("profile/", views.profilepage),
    path("disable/", views.disable_request_user, name="disable-request"),
    path("delete/", views.disable_user, name="disable-user"),
]

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.


class User(AbstractUser):
    username = models.CharField(max_length=60, unique=True)

    def __str__(self):
        if self.username == None:
            return "ERROR-CUSTOMER NAME IS NULL"
        return str(self.username)

    # def __str__(self):
    #    return str(self.username)

    class Meta:
        verbose_name_plural = "User"


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    image = models.ImageField(default="", upload_to="profile_pictures")
    location = models.CharField(max_length=100)

    def __str__(self):
        return self.user.username

    class Meta:
        verbose_name_plural = " User Profile"


class AllLogin(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.user) + ": " + str(self.date)

users/views.py
import os
import requests

from django.shortcuts import render, redirect
from django.contrib.auth import login
from django.contrib.auth.decorators import login_required

from .models import User
from . import models

# Create your views here.


@login_required
def profilepage(request):
    return render(request, "users/profile.html")


def home(request):
    return render(request, "base.html")


@login_required
def disable_request_user(request):
    return render(request, "users/delete_user.html")


@login_required
def disable_user(request):
    pk = request.user.id
    user = User.objects.get(pk=pk)
    if request.user.is_authenticated and request.user.id == user.id:
        if request.method == "POST":
            user.delete()
            return redirect("account_logout")
    return render(request, "users:profile.html")

templates/users/delete_user.html
{% extends "_base.html" %}
{% block content %}

{% load socialaccount %}
{% providers_media_js %}



<div class="row mt-5">
    <div class="col-6" style="justify-content: center; padding: 10em;">
        <form method="POST" action="{% url 'users:disable-user' %}">
            {% csrf_token %}

            <h2>탈퇴하시겠습니까?</h2>
            <button type="submit" class="btn btn-primary">탈퇴하기</button>
        </form>
    </div>
</div>
</div>
{% endblock %}

templates/users/login.html
<h1>Welcome</h1>

{% extends "_base.html" %}
{% block content %}

{% load socialaccount %}
{% providers_media_js %}

<body>
    <div class="container">
        <div class="row mt-5">
            <div class="col-12 text-center">
                <h1>로그인</h1>
            </div>
        </div>
        <div class="row mt-5">
            <div class="col-12">
                {{ error }}
            </div>
        </div>
        <div class="row mt-5">
            <div class="col-6" style="justify-content: center; margin: auto;">
                <form method="POST" action=".">
                    {% csrf_token %}

                    {% for field in form %}
                    <div class="form-group">
                        <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                        <input type="{{ field.field.widget.input_type }}" class="form-control"
                            id="{{ field.id_for_label }}" placeholder="{{ field.label }}" name="{{ field.name }}">

                    </div>
                    {% if field.errors %}
                    <span style="color:red">{{ field.errors }}</span>

                    {% endif %}
                    {% endfor %}
                    <button type="submit" class="btn btn-primary">로그인</button>
                </form>
            </div>
        </div>
    </div>
    <div class="container">
        <div class="row mt-5" style="text-align: center; margin:20px;">
            <div class="col-6" style="justify-content: center; margin: auto;">
                <button type="submit" class="btn" style="border-color:#66CDAA;"><a
                        href="{% provider_login_url 'google' %}">Continue with
                        Google</a></button>
            </div>
        </div>
    </div>
</body>

{% endblock %}

templates/users/profile.html
{% extends '_base.html' %}

{% load static %}
{% load crispy_forms_tags %}
{% block content %}



<div class="container">
    <div class="row">
        <div class="col-md-9" style="margin-bottom: 200px;">
            <h1 class="my-3">About Me</h1>
            <br>
            <h3 class="my-3">{{ user.username }} </h3>
            <hr>
            <h6>가입일 : {{ user.date_joined }}</h6>
            <br>
            <h6>최근 로그인 날짜 : {{ user.last_login }}</h6>
            <hr>

            <a href="{% url 'users:disable-request' %}">탈퇴</a>
            <!--<img width="100px" height="100px" src="{{ user.profile.image.url }}">-->
        </div>
    </div>
</div>
{% endblock %}

templates/users/register.html
<h1>Welcome</h1>

{% extends "_base.html" %}
{% block content %}

{% load socialaccount %}
{% providers_media_js %}

<body>
    <div class="container">
        <div class="row mt-5">
            <div class="col-12 text-center">
                <h1>회원가입</h1>
            </div>
        </div>
        <div class="row mt-2">
            <div class="col-12">
                {{ error }}
            </div>
        </div>
        <div class="row mt-3">
            <div class="col-6" style="justify-content: center; margin: auto;">
                <form method="POST" action=".">
                    {% csrf_token %}

                    {% for field in form %}
                    <div class="form-group">
                        <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                        <input type="{{ field.field.widget.input_type }}" class="form-control"
                            id="{{ field.id_for_label }}" placeholder="{{ field.label }}" name="{{ field.name }}">

                    </div>
                    {% if field.errors %}
                    <span style="color:red">{{ field.errors }}</span>

                    {% endif %}
                    {% endfor %}
                    <button type="submit" class="btn btn-primary">회원가입</button>
                </form>
            </div>
        </div>
    </div>

    <div class="container">
        <div class="row mt-2" style="text-align: center; margin:auto; margin-bottom: 30px;">
            <div class="col-6" style="justify-content: center; margin: auto;">
                <button type="submit" class="btn" style="border-color:#66CDAA;"><a
                        href="{% provider_login_url 'google' %}">Continue
                        with
                        Google</a></button>
            </div>
        </div>
    </div>
</body>

{% endblock %}